# Generated by Django 3.0.7 on 2020-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('asin', models.CharField(max_length=10)),
                ('helpful_num', models.IntegerField()),
                ('helpful_denom', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('text', models.TextField()),
                ('summary', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('reviewer_id', models.CharField(max_length=32)),
                ('reviewer_name', models.CharField(max_length=64)),
            ],
        ),
    ]
