version: "3"
services:
  mysql:
    image: mysql
    volumes:
      - ./mysql/ingestion.sql:/docker-entrypoint-initdb.d/ingestion.sql
      - ./mysql/kindle_reviews.csv:/var/lib/mysql-files/kindle_reviews.csv
    command:
      - "--secure-file-priv=/var/lib/mysql-files/"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: reviews
      MYSQL_USER: django
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  mongo:
    image: mongo
    volumes:
      - ./mongodb/import.sh:/docker-entrypoint-initdb.d/import.sh
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
      - ./mongodb/kindle_metadata_stream.json:/data/mongodb/kindle_metadata_stream.json
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MONGO_INITDB_DATABASE: database
      MONGO_USER: django
      MONGO_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  web:
    build: ./server
    command: gunicorn -b 0.0.0.0:7000 application.wsgi:application
    ports:
      - "7000:7000"
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MONGO_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - mysql
      - mongo

secrets:
  db_root_password:
    file: db_root_password.secret.env
  db_password:
    file: db_password.secret.env
