export interface BookReview {
  reviewerID: string;
  reviewerName: string;
  helpful: number[];
  reviewText: string;
  overall: number;
  summary: string;
  unixReviewTime: number;
  reviewTime: string;
}

export const METADATA = [
  {
    asin: 'B000FA64PA',
    title:
      'Saboteur: Star Wars Legends (Darth Maul) (Short Story) (Star Wars: Darth Maul Book 1)',
    author: 'James Luceno',
    price: 4.58,
    imUrl:
      'http://ecx.images-amazon.com/images/I/4138cT%2BissL._BO2,204,203,200_PIsitb-sticker-v3-big,TopRight,0,-55_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg',
    related: {
      also_bought: [
        'B00513D4HC',
        'B00513HXE2',
        'B000FC1MZU',
        'B000FBFMVG',
        'B00513D47M',
        'B000JMKNQ0',
        'B00513D3IM',
        'B000FA64PK',
        'B000FC1BN8',
        'B0051ANRMW',
        'B00513F9HU',
        'B00E735G9G',
        'B000FA64QO',
        'B0064C3TO2',
        'B00513F9OS',
        'B00A9ET67K',
        'B00513DGWK',
        'B00513E4VM',
        'B00513F9FW',
        'B00513H3YC',
        'B00513HX74',
        'B009MYAQQS',
        'B004NNUYF6',
        'B008ED5HE4',
        'B0051AMYTO',
        'B00513HJI2',
        'B00513FPMY',
        'B00513D3HI',
        'B00513F9CK',
        'B00513FP8S',
        'B000FCKKMG',
        'B00J9RPZG4',
        'B00513E3XG',
        'B00J9RPZKK',
        'B000FCKKUS',
        'B00A5MRE9S',
        'B00A820TKG',
        'B00513E5G6',
        'B000FCKKTO',
        'B000FCKKUI',
        'B000FCKKT4',
        'B000FCKKTE',
        'B00513HCS4',
        'B00513E65Q',
        'B00J9RPZIC',
        'B00513HXAQ',
        'B00513E4GC',
        'B00513HWTS',
        'B00513HCI4',
        'B00513FPBU',
        'B00513HXAG',
        'B00513GR4E',
        'B00513F9E8',
        'B00513HWZM',
        'B00513F9UM',
        'B00513HX0Q',
        'B00513HWXE',
        'B00957T528',
        'B00513F9DE',
        'B00513HWY8',
        'B00513HX2O',
        'B00513F9J8',
        'B00513H3K6',
        'B00BO4GR08',
        'B00513F9BQ',
        'B008LMD2QI',
        'B005O1BYBE',
        'B00513H3P6',
        'B00513HX9W',
        'B00513DH6U',
        'B00513HWIY',
        'B00CGI3J4S',
        'B00513F9PC',
        'B000FBFNQA',
        'B00513DGYS',
        'B00513H3GU',
        'B00A7H2DHY',
        'B00513HX6U',
        'B00513F92K',
        'B00513HX4M',
        'B00513DGPW',
        'B00513FPFQ',
        'B00F1W0DFE',
        'B0018C6Y36',
        'B00513FP2Y',
        'B00513H3WE',
        'B00513DGZ2',
        'B00B0LP3WS',
        'B00A820TFG',
        'B00513HCM0',
        'B000FBFNQK',
        'B00513FPOC',
        'B00513HX4W',
        'B00513HJLO',
        'B00513DGB6',
        'B000FBFNQ0',
        'B00513HJN2',
        'B000SEFLNY',
        'B00513E6E2',
      ],
      buy_after_viewing: [
        'B0051ANRMW',
        'B00E735G9G',
        'B00513D4HC',
        'B00513HX7Y',
      ],
    },
    categories: [
      ['Books', 'Comics & Graphic Novels'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction'],
      ['Books', 'Teen & Young Adult'],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'TV, Movie, Video Game Adaptations',
        'Star Wars',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Teen & Young Adult',
        'Literature & Fiction',
        'Comics & Graphic Novels',
      ],
    ],
  },
  {
    asin: 'B000F83SZQ',
    title: 'A Matter of Policy [An Amy Brewster Mystery]',
    author: 'Sam Merwin Jr.',
    price: 0.0,
    imUrl:
      'http://ecx.images-amazon.com/images/I/51yLqHe%2BFqL._BO2,204,203,200_PIsitb-sticker-v3-big,TopRight,0,-55_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg',
    related: {
      also_bought: [
        'B0080H1C0W',
        'B00LK4ZKOG',
        'B00JZD2PU6',
        'B00JPFAXTY',
        'B00LK4ZMYE',
        'B00LK30NEY',
        'B006LABC8M',
        'B00L1HYMJQ',
        'B00J7X007E',
        'B00LG0HL00',
        'B00CEL5530',
        'B000FA5PUK',
        'B00LNLVQ9Y',
        'B00KBGI38E',
        'B00LDPMLVM',
        'B00KVOC68O',
        'B00A3N25HK',
        'B00K5V449C',
        'B006BE4OUG',
        'B00H9WPHXM',
        'B00D1CPG5I',
        'B0084MZWPO',
        'B00KL13WXK',
        'B00H9ZM782',
        'B00AL2AF8O',
        'B00D0IPCCK',
        'B00JZDM9CA',
        'B000FA5LAO',
        'B00DDW57NW',
        'B00H876DYU',
        'B00EI3E0T2',
        'B00FN9G0KM',
        'B006LAAUHG',
        'B00JX7UVFU',
        'B00K6H2D5W',
        'B00KCA0I96',
        'B00JXRCPNG',
        'B00CV9I2J4',
        'B00L22GJVO',
        'B00EZVS8H2',
        'B00IVC9IQG',
        'B00KOYAQFG',
        'B008AD8TFW',
        'B0036B955G',
        'B00EH3R7WK',
        'B004GXB2DG',
        'B005HAWAZG',
        'B00KVMWJRY',
        'B00K6YZ4CY',
        'B008CJ1R5S',
        'B00ITNWAVM',
        'B009PK83IC',
        'B00F1MU458',
        'B00KUF0KCI',
        'B00DRLACCA',
        'B002G1ZY4S',
        'B00DXO6HR0',
        'B0087KGSNI',
        'B00HD5XVY2',
        'B00ICXDRCU',
        'B003XVYGVC',
        'B00FY54N72',
        'B00HBGISE6',
        'B00KBK4USC',
        'B007GG9XEU',
        'B00AJ1VLOY',
        'B00E6EHFN6',
        'B00IOYDAEW',
        'B00KFOTI72',
        'B008RZQYN2',
        'B00JRDGZN2',
        'B008R8FPFW',
        'B00JL62F48',
        'B006GRNYFE',
        'B00DVL2CVU',
        'B00H92XFA4',
        'B00IJKQH96',
        'B008GNGKIO',
        'B00K39Q7ZK',
        'B00K00LEOG',
        'B00I9FJJWS',
        'B00J9SQW56',
        'B00BEOZCJU',
        'B00EZGSTD0',
        'B003YDXMYG',
        'B00GZR2NZC',
        'B0045UA6F0',
        'B00J16SQFU',
        'B00DPBNP2Q',
        'B00927CLFY',
        'B00H3J4L4M',
        'B00ICP5JLK',
        'B00H4K59DW',
        'B003XVYGWQ',
        'B00HF7J1P6',
      ],
      buy_after_viewing: [
        'B006HCTWVS',
        'B009FZPMFO',
        'B00F1I0C40',
        'B00IVC9IQG',
      ],
    },
    categories: [
      ['Books', 'Literature & Fiction'],
      [
        'Books',
        'Mystery, Thriller & Suspense',
        'Thrillers & Suspense',
        'Suspense',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Mystery, Thriller & Suspense',
        'Suspense',
      ],
    ],
  },
  {
    asin: 'B000FA64PK',
    title:
      'Recovery: Star Wars Legends (The New Jedi Order) (Short Story) (Star Wars: The New Jedi Order)',
    author: 'Troy Denning',
    price: 5.99,
    imUrl:
      'http://ecx.images-amazon.com/images/I/31Ov6Go%2BUFL._BO2,204,203,200_PIsitb-sticker-v3-xsmall,TopRight,2,-18_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg',
    related: {
      also_bought: [
        'B000FA64QO',
        'B00513F934',
        'B00513H3I8',
        'B003F3PKFE',
        'B00513H3WE',
        'B00513E6E2',
        'B00513FP24',
        'B00513HWT8',
        'B00513DHJ2',
        'B00513HJN2',
        'B00513HX4W',
        'B00513FPEC',
        'B00513D3F0',
        'B00513HJW8',
        'B00513F9KM',
        'B000FBFNQ0',
        'B000FBFMVG',
        'B00513F9JS',
        'B00513HX6U',
        'B000FBFNQK',
        'B000JMKNQ0',
        'B000FC1MZU',
        'B000FC1BN8',
        'B000FBFNQA',
        'B000FA64PA',
        'B000FCKKOE',
        'B000FCKMDS',
        'B000GCFCIM',
        'B00A9ET67K',
        'B000SEGVBA',
        'B0010SENMC',
        'B000WJQU26',
        'B000XPNUTU',
        'B000SEGWWI',
        'B000VTUDR0',
        'B000SEFLNY',
        'B0018C6Y36',
        'B000UZQHX4',
        'B001FA0I7Y',
        'B00513FP2Y',
        'B001NLKUMI',
        'B00513HJLO',
        'B0036S4CDE',
        'B00513DGB6',
        'B002L9MYZC',
        'B0036S4APE',
        'B001NLL8RO',
        'B00513H3RE',
        'B00513E5NO',
        'B003F3PM70',
        'B00513HWSE',
        'B00513FPOC',
        'B00513H3GU',
        'B00513DGUC',
        'B00513E3HW',
        'B004J4WM7M',
        'B004J4WNKS',
        'B00513HX9W',
        'B00513E5SY',
        'B005DXOOWE',
        'B00513DGES',
        'B0064C3TO2',
        'B00513DGTI',
        'B005O1BYBE',
        'B00513HWQG',
        'B00513DGC0',
        'B00B0LP3WS',
        'B00513F952',
        'B00513E3V8',
        'B00513D3QE',
        'B00957T528',
        'B00513DGUM',
        'B00513F9PW',
        'B00CGI3J4S',
        'B00513F9FW',
        'B00E735G9G',
        'B00513DGZ2',
        'B005X0JI6E',
        'B00513HWTS',
        'B00A5MRE9S',
        'B00513HJKU',
        'B00513D4HC',
        'B00513FPBU',
        'B00513D3B4',
        'B00513HJXC',
        'B008ED5HE4',
        'B00513D47M',
        'B00513F9UM',
        'B00513FPMY',
        'B00513HKF4',
        'B0051ANRMW',
        'B00513F9DE',
        'B00513F9HU',
        'B00513HWXE',
        'B00513H3YC',
        'B00513F9E8',
        'B00513F9OS',
        'B008LMD2QI',
        'B00513D3HI',
        'B00513H3ME',
      ],
      buy_after_viewing: [
        'B00513F934',
        'B00513H3I8',
        'B000JMKNQ0',
        'B003F3PKFE',
      ],
    },
    categories: [
      ['Books', 'Comics & Graphic Novels', 'Graphic Novels', 'Science Fiction'],
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Action & Adventure'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction', 'Adventure'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction', 'Space Opera'],
      ['Books', 'Teen & Young Adult'],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Comics & Graphic Novels',
        'Graphic Novels',
        'Action & Adventure',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Comics & Graphic Novels',
        'Graphic Novels',
        'Science Fiction',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Action & Adventure',
        'Fantasy',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'Adventure',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'Space Opera',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'TV, Movie, Video Game Adaptations',
        'Star Wars',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Teen & Young Adult',
        'Literature & Fiction',
        'Comics & Graphic Novels',
      ],
    ],
  },
  {
    asin: 'B000FA64QO',
    title:
      'Ylesia: Star Wars Legends (The New Jedi Order) (Star Wars: The New Jedi Order)',
    author: 'Walter Jon Williams',
    price: 5.99,
    imUrl:
      'http://ecx.images-amazon.com/images/I/51h5NLeMStL._BO2,204,203,200_PIsitb-sticker-v3-big,TopRight,0,-55_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg',
    related: {
      also_bought: [
        'B00513D3F0',
        'B00513HJW8',
        'B00513FPEC',
        'B000FA64PK',
        'B00513F9KM',
        'B00513HJN2',
        'B00513F9JS',
        'B00513HX6U',
        'B00513DHJ2',
        'B00513FP24',
        'B00513E6E2',
        'B00513H3WE',
        'B00513H3I8',
        'B00513F934',
        'B003F3PKFE',
        'B000FCKKOE',
        'B000FBFMVG',
        'B000FCKMDS',
        'B00513HWT8',
        'B000GCFCIM',
        'B00513HX4W',
        'B000FC1MZU',
        'B000FC1BN8',
        'B000JMKNQ0',
        'B000FBFNQ0',
        'B000FBFNQK',
        'B000FBFNQA',
        'B000WJQU26',
        'B0010SENMC',
        'B000SEGVBA',
        'B000SEFLNY',
        'B000UZQHX4',
        'B000SEGWWI',
        'B000VTUDR0',
        'B0018C6Y36',
        'B000FA64PA',
        'B000XPNUTU',
        'B001FA0I7Y',
        'B00A9ET67K',
        'B00513H3GU',
        'B001NLKUMI',
        'B002L9MYZC',
        'B001NLL8RO',
        'B00513HX9W',
        'B0036S4APE',
        'B0036S4CDE',
        'B003F3PM70',
        'B004J4WNKS',
        'B004J4WM7M',
        'B00513HJLO',
        'B00513FP2Y',
        'B00513DGB6',
        'B005DXOOWE',
        'B00513E5NO',
        'B00513FPOC',
        'B00513DGUC',
        'B00513HWSE',
        'B00513H3RE',
        'B00513E5SY',
        'B00513E3HW',
        'B0064C3TO2',
        'B00513DGES',
        'B00513HJKU',
        'B00513HWTS',
        'B00513DGTI',
        'B00E735G9G',
        'B005X0JI6E',
        'B00513HWQG',
        'B00A5MRE9S',
        'B00513F9PW',
        'B00513FPBU',
        'B00513DGC0',
        'B00513D3QE',
        'B00B0LP3WS',
        'B00513DGUM',
        'B00513E3V8',
        'B005O1BYBE',
        'B00513F9DE',
        'B00513F9UM',
        'B00513HCR0',
        'B00513F9J8',
        'B00513F952',
        'B00957T528',
        'B00513D3B4',
        'B00CGI3J4S',
        'B00513D47M',
        'B008ED5HE4',
        'B008LMD2QI',
        'B00513F9FW',
        'B00513F92K',
        'B00LNRWTSU',
        'B004NNUYF6',
        'B00513HX2O',
        'B00513HCM0',
        'B00513DGYS',
        'B00513D4HC',
        'B00513DGZ2',
        'B00513HJXC',
        'B00513F9OS',
        'B00513F9HU',
      ],
      buy_after_viewing: [
        'B00513D3F0',
        'B000FBFNQA',
        'B00513F9JS',
        'B00513E5G6',
      ],
    },
    categories: [
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Movie Tie-Ins'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction', 'Space Opera'],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Genre Fiction',
        'Movie Tie-Ins',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'Space Opera',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'TV, Movie, Video Game Adaptations',
        'Star Wars',
      ],
    ],
  },
  {
    asin: 'B000FBFMVG',
    title:
      'A Forest Apart: Star Wars Legends (Short Story) (Star Wars - Legends)',
    author: 'Troy Denning',
    price: 1.99,
    imUrl:
      'http://ecx.images-amazon.com/images/I/31xnW4Cwv8L._BO2,204,203,200_PIsitb-sticker-v3-xsmall,TopRight,2,-18_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg',
    related: {
      also_bought: [
        'B000FC1MZU',
        'B000FC1BN8',
        'B00513F952',
        'B000FA64PK',
        'B000JMKNQ0',
        'B000FA64QO',
        'B000FA64PA',
        'B00A9ET67K',
        'B00513D3B4',
        'B00513E3V8',
        'B00513F9PW',
        'B00513HJKU',
        'B00513DHAG',
        'B00513HWQG',
        'B00513DGC0',
        'B00513HWTI',
        'B00513DGUM',
        'B00513E3HW',
        'B00513HWSE',
        'B00513DGUC',
        'B00513E4M6',
        'B00513DGTI',
        'B00513H3RE',
        'B00513E5GG',
        'B00513D3QE',
        'B00513H3ME',
        'B00513HJLO',
        'B00513DGB6',
        'B00513E5NO',
        'B00513DGES',
        'B00513FPBK',
        'B00513HX1A',
        'B00513HKF4',
        'B00513HJXC',
        'B00513H3N8',
        'B0064C3TO2',
        'B00CGI3J4S',
        'B005O1BYBE',
        'B005X0JI6E',
        'B00513FP2Y',
        'B008LMD2QI',
        'B00513HWUM',
        'B00957T528',
        'B00513HWTS',
        'B00513DGZ2',
        'B00B0LP3WS',
        'B00513HX7Y',
        'B001FA0I7Y',
        'B00A5MRE9S',
        'B00513HXBA',
        'B00513HX2O',
        'B00513FPBU',
        'B00513HX4W',
        'B00513FPOC',
        'B000FBFNQK',
        'B00513E5SY',
        'B00513H3GU',
        'B00513F9DE',
        'B00513F9PC',
        'B000FBFNQ0',
        'B00F1W0DFE',
        'B00513FPFQ',
        'B00513HX9W',
        'B00513HWXE',
        'B00513H3WE',
        'B00513F9UM',
        'B00513D4HC',
        'B00513HWT8',
        'B00513HCM0',
        'B00513HWZM',
        'B00513DHJ2',
        'B00BO4GR08',
        'B003F3PKFE',
        'B00513D47M',
        'B000FBFNQA',
        'B008ED5HE4',
        'B00513HX4M',
        'B00513H3P6',
        'B00513F9CA',
        'B00513HWXO',
        'B00513F9E8',
        'B00513F9FW',
        'B000FCKMDS',
        'B00513E6E2',
        'B000FCKKUS',
        'B000FCKKOE',
        'B004J4WM7M',
        'B00513HJN2',
        'B00513DH6U',
        'B000GCFCIM',
        'B00513FPEC',
        'B00513FP24',
        'B00513H3I8',
        'B00513HX6U',
        'B000FCKKUI',
        'B003F3PM70',
        'B00513DGPW',
        'B00A820TFG',
        'B005DXOOWE',
        'B00513F934',
      ],
      buy_after_viewing: [
        'B000JMKNQ0',
        'B000FC1BN8',
        'B00513F952',
        'B00A9ET67K',
      ],
    },
    categories: [
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Action & Adventure'],
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Movie Tie-Ins'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction', 'Adventure'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction', 'Space Opera'],
      [
        'Kindle Store',
        'Kindle Short Reads',
        'Two hours or more (65-100 pages)',
        'Literature & Fiction',
      ],
      [
        'Kindle Store',
        'Kindle Short Reads',
        'Two hours or more (65-100 pages)',
        'Science Fiction & Fantasy',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Genre Fiction',
        'Movie Tie-Ins',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'Adventure',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'Space Opera',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'TV, Movie, Video Game Adaptations',
        'Star Wars',
      ],
    ],
  },
  {
    asin: 'B000FC1BN8',
    title: "Fool's Bargain: Star Wars Legends (Novella) (Star Wars - Legends)",
    author: 'Timothy Zahn',
    price: 4.59,
    imUrl:
      'http://ecx.images-amazon.com/images/I/51WMe3%2BrLhL._BO2,204,203,200_PIsitb-sticker-v3-big,TopRight,0,-55_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg',
    related: {
      also_bought: [
        'B000FBFMVG',
        'B00A9ET67K',
        'B000JMKNQ0',
        'B000FC1MZU',
        'B00513FP2Y',
        'B000FA64PK',
        'B000FA64QO',
        'B000FA64PA',
        'B00513FPOC',
        'B00513E5SY',
        'B00513HJLO',
        'B00513F9OS',
        'B00513DGZ2',
        'B00513H3RE',
        'B00513DGB6',
        'B00513FPFQ',
        'B005O1BYBE',
        'B000FBFNQA',
        'B000FBFNQ0',
        'B008LMD2QI',
        'B000FBFNQK',
        'B00513E5NO',
        'B00513HX4W',
        'B00513HWSE',
        'B00513HWT8',
        'B00513E3HW',
        'B00513DGUC',
        'B003F3PKFE',
        'B00513H3I8',
        'B00513F934',
        'B00513FP24',
        'B00513E3V8',
        'B00513H3WE',
        'B00513DHJ2',
        'B00513E6E2',
        'B00513HJN2',
        'B00513DGTI',
        'B00CGI3J4S',
        'B00513DGES',
        'B00513HJKU',
        'B00513HX6U',
        'B00513D3F0',
        'B00513H3GU',
        'B0064C3TO2',
        'B00F1W0DFE',
        'B00513FPEC',
        'B001FA0I7Y',
        'B005X0JI6E',
        'B00513F952',
        'B00957T528',
        'B00513F9JS',
        'B00513F9KM',
        'B00513F9PW',
        'B00513HJW8',
        'B00513HX9W',
        'B00513HX2O',
        'B00513HJXC',
        'B00513D3QE',
        'B00BO4GR08',
        'B000FCKKOE',
        'B00B0LP3WS',
        'B000GCFCIM',
        'B00513HKF4',
        'B00BHM8BBA',
        'B00E735G9G',
        'B000FCKMDS',
        'B00A5MRE9S',
        'B00513HJI2',
        'B00513HX1A',
        'B00513HCR0',
        'B008ED5HE4',
        'B00513HWQG',
        'B00513F9DE',
        'B00513DGC0',
        'B0051ANRMW',
        'B00513F92K',
        'B00513DGUM',
        'B00J9RPZIC',
        'B00513FPBU',
        'B000FCKKMG',
        'B00E6ETSG8',
        'B00513HWXE',
        'B00A7H2DHY',
        'B00513DHAG',
        'B00A820TFG',
        'B000FCKKUI',
        'B00513D3B4',
        'B00513F9UM',
        'B00513HX7Y',
        'B00513DGYS',
        'B000FCKKTO',
        'B00513HWTS',
        'B00513F9HU',
        'B00513F9J8',
        'B00513HWZM',
        'B00513FPBK',
        'B00513F9E8',
        'B00513E4VM',
        'B00513HWUM',
      ],
      buy_after_viewing: [
        'B00513HX7Y',
        'B008LMD2QI',
        'B00513FP2Y',
        'B000JMKNQ0',
      ],
    },
    categories: [
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Movie Tie-Ins'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction', 'Adventure'],
      ['Books', 'Science Fiction & Fantasy', 'Science Fiction', 'Space Opera'],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Genre Fiction',
        'Movie Tie-Ins',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'Adventure',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'Space Opera',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Science Fiction & Fantasy',
        'Science Fiction',
        'TV, Movie, Video Game Adaptations',
        'Star Wars',
      ],
    ],
  },
  {
    asin: 'B000FC1TG2',
    title: 'The Iron Marshal: A Novel',
    author: "Louis L'Amour",
    description:
      "Tom Shanaghy was iron-tough, but he was no lawman. Back in New  York, he'd been the strong-arm for an infamous Irish gang. But when he  jumped a westbound train to escape a deadly street war, fate sent him  to a small Kansas town on the brink of its own violent battle. The  townspeople were sorely in need of a marshal, and they convinced  Shanaghy to pin on the badge. Now he must wade into the fight of his  life, one that will show him just how tough this new land really is.",
    price: 5.12,
    imUrl:
      'http://ecx.images-amazon.com/images/I/41uIBiFzcyL._BO2,204,203,200_PIsitb-sticker-v3-big,TopRight,0,-55_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg',
    related: {
      also_bought: [
        'B000FC1N0Y',
        'B000FC2MC2',
        'B000FBJDZC',
        'B000FC1GA6',
        'B000FC2MB8',
        'B000FC0XXM',
        'B000FC2O6Q',
        'B000FC2O6G',
        'B000FC2K4W',
        'B000FC1RSM',
        'B000FC2ISU',
        'B000FCK2V0',
        'B000FC1AHA',
        'B000FC2JNY',
        'B000FC1LTM',
        'B000FCKBE8',
        'B000FC1QC4',
        'B000FC27RW',
        'B000FC1QP6',
        'B000FBJDS4',
        'B000FC0ZHQ',
        'B000FC2MBI',
        'B000FC1RX2',
        'B000FCK1YS',
        'B000FC2O66',
        'B000FC0ZGW',
        'B000FC2RMC',
        'B000FC1AHU',
        'B000FC2K56',
        'B000FC1ME6',
        'B000FC1TGC',
        'B000FCK0H6',
        'B000FC2K4C',
        'B000FC1AHK',
        'B000FC1QQ0',
        'B000FC1V3S',
        'B000FC2LW8',
        'B000FC2K5G',
        'B000FBJDZM',
        'B000FC2MBS',
        'B000FC2PLA',
        'B000FC1QPQ',
        'B000FC0XXC',
        'B000FC1V4C',
        'B000FCKBDY',
        'B000FCK8ZA',
        'B000FC2RMW',
        'B000FCKBD4',
        'B000FC0ZHG',
        'B000FC1BHE',
        'B000FC0XWS',
        'B000FCK1YI',
        'B000FCK0GW',
        'B000FC1VPQ',
        'B000FC1LTW',
        'B000FC1QQA',
        'B005MHI0GW',
        'B000FC1QPG',
        'B000FCKCCE',
        'B000FC2ISK',
        'B000FC1V42',
        'B000FBJAZU',
        'B000FC0XX2',
        'B000FC1V3I',
        'B000FC1MDW',
        'B002IPZK00',
        'B000FC29IO',
        'B000FBJAYG',
        'B000FBJDR0',
        'B000FBJAYQ',
        'B000FC1B2E',
        'B000FC1GAG',
        'B000FC0ZGM',
        'B000FBJB1S',
        'B000FBJAZA',
        'B000FCKBDO',
        'B000FCK3Z0',
        'B000FCK4GI',
        'B000FC2K4M',
        'B00LEVHH6O',
        'B000FBJAZ0',
        'B000FBJB0O',
        'B005MHI11G',
        'B000FBJB04',
        'B000FBJAZK',
        'B000FC2O70',
        'B000FC2RMM',
        'B000FBJAXW',
        'B000FCKBDE',
        'B000FC27SG',
        'B000FC27S6',
        'B000FC0ZH6',
        'B000FCK2VK',
        'B000FC289O',
        'B002IPZJSI',
        'B000FC1AH0',
        'B000FBJF5U',
        'B003YJF0DG',
        'B000FC2RN6',
        'B005MHHRVG',
      ],
      buy_after_viewing: [
        'B000FC2MC2',
        'B000FC1QC4',
        'B000FC1N0Y',
        'B000FBJDZC',
      ],
    },
    categories: [
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Action & Adventure'],
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Historical'],
      ['Books', 'Literature & Fiction', 'Genre Fiction', 'Westerns'],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Action & Adventure',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Genre Fiction',
        'Westerns',
        'Contemporary',
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Genre Fiction',
        'Westerns',
        "Louis L'Amour",
      ],
      [
        'Kindle Store',
        'Kindle eBooks',
        'Literature & Fiction',
        'Historical Fiction',
      ],
    ],
  },
];
export const REVIEWS = [
  {
    reviewerID: 'A1F6404F1VG29J',
    asin: 'B000F83SZQ',
    reviewerName: 'Avidreader',
    helpful: [0, 0],
    reviewText:
      "I enjoy vintage books and movies so I enjoyed reading this book.  The plot was unusual.  Don't think killing someone in self-defense but leaving the scene and the body without notifying the police or hitting someone in the jaw to knock them out would wash today.Still it was a good read for me.",
    overall: 5.0,
    summary: 'Nice vintage story',
    unixReviewTime: 1399248000,
    reviewTime: '05 5, 2014',
  },

  {
    reviewerID: 'AN0N05A9LIJEQ',
    asin: 'B000F83SZQ',
    reviewerName: 'critters',
    helpful: [2, 2],
    reviewText:
      "This book is a reissue of an old one; the author was born in 1910. It's of the era of, say, Nero Wolfe. The introduction was quite interesting, explaining who the author was and why he's been forgotten; I'd never heard of him.The language is a little dated at times, like calling a gun a &#34;heater.&#34;  I also made good use of my Fire's dictionary to look up words like &#34;deshabille&#34; and &#34;Canarsie.&#34; Still, it was well worth a look-see.",
    overall: 4.0,
    summary: 'Different...',
    unixReviewTime: 1388966400,
    reviewTime: '01 6, 2014',
  },

  {
    reviewerID: 'A795DMNCJILA6',
    asin: 'B000F83SZQ',
    reviewerName: 'dot',
    helpful: [2, 2],
    reviewText:
      "This was a fairly interesting read.  It had old- style terminology.I was glad to get  to read a story that doesn't have coarse, crasslanguage.  I read for fun and relaxation......I like the free ebooksbecause I can check out a writer and decide if they are intriguing,innovative, and have enough of the command of Englishthat they can convey the story without crude language.",
    overall: 4.0,
    summary: 'Oldie',
    unixReviewTime: 1396569600,
    reviewTime: '04 4, 2014',
  },

  {
    reviewerID: 'A1FV0SX13TWVXQ',
    asin: 'B000F83SZQ',
    reviewerName: 'Elaine H. Turley "Montana Songbird"',
    helpful: [1, 1],
    reviewText:
      "I'd never read any of the Amy Brewster mysteries until this one..  So I am really hooked on them now.",
    overall: 5.0,
    summary: 'I really liked it.',
    unixReviewTime: 1392768000,
    reviewTime: '02 19, 2014',
  },

  {
    reviewerID: 'A3SPTOKDG7WBLN',
    asin: 'B000F83SZQ',
    reviewerName: 'Father Dowling Fan',
    helpful: [0, 1],
    reviewText:
      'If you like period pieces - clothing, lingo, you will enjoy this mystery.  Author had me guessing at least 2/3 of the way through.',
    overall: 4.0,
    summary: 'Period Mystery',
    unixReviewTime: 1395187200,
    reviewTime: '03 19, 2014',
  },

  {
    reviewerID: 'A1RK2OCZDSGC6R',
    asin: 'B000F83SZQ',
    reviewerName: 'ubavka seirovska',
    helpful: [0, 0],
    reviewText:
      'A beautiful in-depth character description makes it like a fast pacing movie. It is a pity Mr Merwin did not write 30 instead only 3 of the Amy Brewster mysteries.',
    overall: 4.0,
    summary: 'Review',
    unixReviewTime: 1401062400,
    reviewTime: '05 26, 2014',
  },

  {
    reviewerID: 'A2HSAKHC3IBRE6',
    asin: 'B000F83SZQ',
    reviewerName: 'Wolfmist',
    helpful: [0, 0],
    reviewText:
      "I enjoyed this one tho I'm not sure why it's called An Amy Brewster Mystery as she's not in it very much. It was clean, well written and the characters well drawn.",
    overall: 4.0,
    summary: 'Nice old fashioned story',
    unixReviewTime: 1402358400,
    reviewTime: '06 10, 2014',
  },

  {
    reviewerID: 'A3DE6XGZ2EPADS',
    asin: 'B000F83SZQ',
    reviewerName: 'WPY',
    helpful: [1, 1],
    reviewText:
      "Never heard of Amy Brewster. But I don't need to like Amy Brewster to like this book. Actually, Amy Brewster is a side kick in this story, who added mystery to the story not the one resolved it. The story brings back the old times, simple life, simple people and straight relationships.",
    overall: 4.0,
    summary: 'Enjoyable reading and reminding the old times',
    unixReviewTime: 1395446400,
    reviewTime: '03 22, 2014',
  },

  {
    reviewerID: 'A1UG4Q4D3OAH3A',
    asin: 'B000FA64PA',
    reviewerName: 'dsa',
    helpful: [0, 0],
    reviewText:
      'Darth Maul working under cloak of darkness committing sabotage now that is a story worth reading many times over.  Great story.',
    overall: 5.0,
    summary: 'Darth Maul',
    unixReviewTime: 1381449600,
    reviewTime: '10 11, 2013',
  },

  {
    reviewerID: 'AQZH7YTWQPOBE',
    asin: 'B000FA64PA',
    reviewerName: 'Enjolras',
    helpful: [0, 0],
    reviewText:
      "This is a short story focused on Darth Maul's role in helping the Trade Federation gain a mining colony. It's not bad, but it's also nothing exceptional. It's fairly short so we don't really get to see any characters develop. The few events that do happen seem to go by quickly, including what should have been major battles. The story is included in the novelShadow Hunter (Star Wars: Darth Maul), which is worth reading, so don't bother to buy this one separately.",
    overall: 4.0,
    summary: 'Not bad, not exceptional',
    unixReviewTime: 1297555200,
    reviewTime: '02 13, 2011',
  },

  {
    reviewerID: 'A1ZT7WV0ZUA0OJ',
    asin: 'B000FA64PA',
    reviewerName: 'Mike',
    helpful: [0, 0],
    reviewText:
      "I think I have this one in both book and audio. It is a good story either way. good ol' Maul.",
    overall: 5.0,
    summary: 'Audio and book',
    unixReviewTime: 1390780800,
    reviewTime: '01 27, 2014',
  },

  {
    reviewerID: 'A2ZFR72PT054YS',
    asin: 'B000FA64PA',
    reviewerName: 'monkeyluis',
    helpful: [0, 0],
    reviewText:
      "Title has nothing to do with the story.  I did enjoy it though.  Good short story about Darth Maul setting up two corporations against each other.  All in the end to help Darth Sidious' rise to power.  Won't take you long to read & it's cheap.  Go for it.",
    overall: 4.0,
    summary: 'Darth Maul...the brother I never had.',
    unixReviewTime: 1316217600,
    reviewTime: '09 17, 2011',
  },

  {
    reviewerID: 'A2QK1U70OJ74P',
    asin: 'B000FA64PA',
    reviewerName: 'Sharon Deem',
    helpful: [0, 0],
    reviewText:
      'Well written. Interesting to see Sideous (through Maul) maneuvering events to fit his plan. We see human nature at work. But no good guys to root for. Even Rurit is a helpless pawn.',
    overall: 3.0,
    summary: 'Not bad; it is well written',
    unixReviewTime: 1388448000,
    reviewTime: '12 31, 2013',
  },

  {
    reviewerID: 'A3SZMGJMV0G16C',
    asin: 'B000FA64PK',
    reviewerName: 'Andrew Pruette "Rancors Love to Read"',
    helpful: [0, 0],
    reviewText:
      "Troy Denning's novella Recovery was originally published in e-book form and is a short tale set after the events of Kathy Tyers' Balance Point. Han and Leia Solo's relationship was fractured early in the Yuuzhan Vong invasion by the death of someone in the family, and the books prior to Recovery, notably the Agents of Chaos duology, spent time exploring Han's journey to reclaim himself from his demons and Leia's efforts to be patient with the process.  Ms. Tyers reunited the couple in Balance Point as the battle for Duros commenced, but it is in this short story that they truly begin the emotional healing process.We start on Corellia with a battle in a hospital and an appearance from Han's rogue cousin Thracken Sal-Solo. It's good to touch base on what Sal-Solo has been up to since he fired the Centerpoint weapon earlier in the New Jedi Order. Mr. Denning uses this story to introduce a group of his preferred characters, a tight-knit group of saurian Barabel Jedi. Here they are accompanied by an entertainingly non-conventional, salt-addicted Arcona Jedi as well as a human Jedi, Master Eelysa, known for her lengthy and complicated solo missions. The Barabel come into full play in Mr. Denning's own Star by Star and are memorable characters: it's welcome, if certainly not essential, to have their background more fully fleshed out here.In fact, the Jedi provide the most entertaining aspect of Recovery. The Solo reactions to the explicitly non-human worldview of the Barabel are genuinely funny, especially as they struggle to comprehend Barabel humor. Mr. Denning handles the evolution of their relationship and concurrent healing capably enough, although no aspect of this jumps out at me as especially memorable. The final two chapters take the story on a race to Coruscant to stop a potentially disastrous Senate vote. This portion feels rushed, as if it was constrained by the limitations of being a short e-book, but it brings events to a satisfying close nevertheless.Certainly not an essential read, Recovery does flesh out aspects of the New Jedi Order and it worth a look to anyone reading that part of the saga, especially if you are a fan of Mr. Denning's later novels and want to get a bit more insight into the origin of a couple of his preferred Jedi characters.",
    overall: 3.0,
    summary: 'Han and Leia reunited and Barabel Jedi introduced',
    unixReviewTime: 1331769600,
    reviewTime: '03 15, 2012',
  },

  {
    reviewerID: 'A3H8PE1UFK04JZ',
    asin: 'B000FA64PK',
    reviewerName: 'Caleb Watts',
    helpful: [0, 0],
    reviewText:
      "I am not for sure on how much of a difference the short story has on the overall series (I haven't read on yet), but I would recommend that anyone buy it to help them understand the whole series better.P.S.- The series is one of the best of all the Star Wars series.",
    overall: 5.0,
    summary: 'Possibly Important',
    unixReviewTime: 1368316800,
    reviewTime: '05 12, 2013',
  },

  {
    reviewerID: 'A2EN84QHDRZLP2',
    asin: 'B000FA64PK',
    reviewerName: 'Carl craft',
    helpful: [0, 0],
    reviewText:
      'I really enjoyed the book. Had the normal back against the wall moments. It even had laugh out loud moments.',
    overall: 5.0,
    summary: 'Another read',
    unixReviewTime: 1388620800,
    reviewTime: '01 2, 2014',
  },

  {
    reviewerID: 'A1UG4Q4D3OAH3A',
    asin: 'B000FA64PK',
    reviewerName: 'dsa',
    helpful: [0, 0],
    reviewText:
      'Great read enjoyed every minute of it .  I think it answers some questions that are out there about this series.',
    overall: 5.0,
    summary: 'Recovery',
    unixReviewTime: 1383004800,
    reviewTime: '10 29, 2013',
  },

  {
    reviewerID: 'A38Z3Q6DTDIH9J',
    asin: 'B000FA64PK',
    reviewerName: 'Jimmy J. Shaw "oldbent1"',
    helpful: [4, 4],
    reviewText:
      "Another well written eBook by Troy Denning, but why is it put where it is? Why not a part of Balance Point? It is well written and belongs in the new Jedi Order. I just don't think it should stand alone. It is fun and fast to read on my Kindle, but not even in paperback????",
    overall: 3.0,
    summary: 'Star Wars: The New Jedi Order: Recovery',
    unixReviewTime: 1239840000,
    reviewTime: '04 16, 2009',
  },

  {
    reviewerID: 'A1ZT7WV0ZUA0OJ',
    asin: 'B000FA64PK',
    reviewerName: 'Mike',
    helpful: [0, 1],
    reviewText:
      'This one promises to be another good book. I have been reading through the series and have not gotten this far yet.',
    overall: 5.0,
    summary: 'my collection',
    unixReviewTime: 1390780800,
    reviewTime: '01 27, 2014',
  },

  {
    reviewerID: 'A22CW0ZHY3NJH8',
    asin: 'B000FA64PK',
    reviewerName: 'Noname',
    helpful: [0, 0],
    reviewText:
      'I have a version of "Star by Star" that does not include the novella "Recovery," so I downloaded this book onto my Fire.  "Recovery" tells of Leia\'s recovery after she was nearly killed in "Balance Point."  If it was meant to tell the story of the healing of Han and Leia\'s relationship, it surely failed.  There was far too much action to attempt much more than a few brief moments or reconciliation.  They have a deeper understanding of each other but not much time to work on it.Is it a necessary read?  Not really.  I could have skipped it (I actually did) and not miss much.  It felt like the extraneous part of a book that had been edited out, like in the DVD\'s, where it\'s billed as the extras.  People pay to see those extras.  I did.  It was worth it, but probably not to everyone.',
    overall: 4.0,
    summary: 'Not a necessary read, but I liked it',
    unixReviewTime: 1342742400,
    reviewTime: '07 20, 2012',
  },

  {
    reviewerID: 'A2QK1U70OJ74P',
    asin: 'B000FA64PK',
    reviewerName: 'Sharon Deem',
    helpful: [0, 0],
    reviewText:
      'Excellent! Very well written story, very exciting with LOTS of action. The bad guys trying to kill Leia and Han. Viki Shesh is introduced.',
    overall: 5.0,
    summary: 'Fits right into New Jedi Order timeline',
    unixReviewTime: 1388448000,
    reviewTime: '12 31, 2013',
  },

  {
    reviewerID: 'A3SZMGJMV0G16C',
    asin: 'B000FA64QO',
    reviewerName: 'Andrew Pruette "Rancors Love to Read"',
    helpful: [0, 0],
    reviewText:
      "With Ylesia, a novella originally published in e-book form, Walter Jon Williams gets an opportunity to insert further story into his novel Destiny's Way. The events of Ylesia take place midway through that book, so this is a good read to tackle immediately after finishing Destiny's Way. The novella follows a New Republic mission to the titular planet, which is serving as the capital of the traitorous Peace Brigade and houses their attempt at a Senate. The Peace Brigade promote capitulation to the Yuuzhan Vong and have served as a human counterpoint to the efforts of the Jedi and the more heroic members of the New Republic throughout the New Jedi Order. They are a logical part of the story but not one I've found terribly interesting, as we rarely get anything told from their point-of-view, making them rather cardboard as adversaries.Yleisa brings back Thracken Sal-Solo in an entertaining plotline which sees him forcibly installed as the President of the Peace Brigade. This doesn't fit well with Sal-Solo's plans to better his own galactic situation but he displays a knack for adaption and survival not unlike that of his famous cousin Han Solo. Ylesia itself, a major source of the drug spice in the Star Wars galaxy, will be familiar to readers of A. C. Crispin's Han Solo Trilogy, and it's nice to see it return.For the most part Yleisa doesn't advance the story of Destiny's Way much: primarily, it delivers some closure to the Peace Brigade subplot. Sal-Solo was the most memorable aspect, as some of the space battle and ground assault material following the New Republic's invasion of the system felt like material I've read an awful lot of times before.  Ylesia is a solid enough little story but I would only recommend it to someone going through the entire New Jedi Order and wanting a little more.",
    overall: 2.0,
    summary: 'Minor New Jedi Order side story',
    unixReviewTime: 1331769600,
    reviewTime: '03 15, 2012',
  },

  {
    reviewerID: 'A1UG4Q4D3OAH3A',
    asin: 'B000FA64QO',
    reviewerName: 'dsa',
    helpful: [0, 0],
    reviewText:
      "Great book couldn't put it down.  The story expands events in the new Jedi order series.  Good writer in Walter Jon Williams.",
    overall: 5.0,
    summary: 'Ylesia',
    unixReviewTime: 1391472000,
    reviewTime: '02 4, 2014',
  },

  {
    reviewerID: 'AQZH7YTWQPOBE',
    asin: 'B000FA64QO',
    reviewerName: 'Enjolras',
    helpful: [2, 2],
    reviewText:
      "Most of the New Jedi Order books focus on the Solo kids, to the extent that some are viewed as \"Jacen books\" or \"Jania books.\" The novella Ylesia is if anything a book starring Thrackan Sal-Solo. Thrackan is forcibly recruited by the Yuuzhan Vong to become president of the Peace Brigade Republic. However, the New Republic forces also choose to attack Ylesia. There's nothing new or terribly exciting in the novel, but it's a nice side story. It's written in a similar style asDestiny's Way (Star Wars: The New Jedi Order, Book 14), which isn't surprising as they're both by the same author. This short story actually takes place during the novel, so I'd recommend reading the novel first so Ylesia doesn't spoil any surprises.",
    overall: 4.0,
    summary: 'A Thrackan story',
    unixReviewTime: 1305590400,
    reviewTime: '05 17, 2011',
  },

  {
    reviewerID: 'A1ZT7WV0ZUA0OJ',
    asin: 'B000FA64QO',
    reviewerName: 'Mike',
    helpful: [0, 0],
    reviewText:
      'I was hoping to find this one in book form. The story looks like it will be good when I get that far in the series.',
    overall: 5.0,
    summary: 'my e- collection',
    unixReviewTime: 1390780800,
    reviewTime: '01 27, 2014',
  },

  {
    reviewerID: 'A22CW0ZHY3NJH8',
    asin: 'B000FA64QO',
    reviewerName: 'Noname',
    helpful: [0, 0],
    reviewText:
      'The events of "Ylesia" take place during "Destiny\'s Way."  If you\'ve read "Destiny\'s Way," you will see it mentioned in passing.Jaina and Jacen go to Ylesia to fight the Peace Brigade to show them that it\'s not good to align themselves with the enemy.  From there, it is page after page of battle scenes.  It is endless.  One huge chapter.  It\'s like the chapter that was cut out for good reason."Ylesia" doesn\'t advance "Destiny\'s Way" or "The New Jedi Order" in any way that I could tell.  We don\'t learn anything new.  There is no insight.  If I had skipped it, I wouldn\'t have missed anything.If you don\'t mind reading in PDF, "Ylesia" is available free from Del Rey.  If you Google, you\'ll see it linked to the Wayback machine and it\'s still there.',
    overall: 3.0,
    summary: 'One huge chapter',
    unixReviewTime: 1344297600,
    reviewTime: '08 7, 2012',
  },

  {
    reviewerID: 'A3AZH0OO0GUAI3',
    asin: 'B000FBFMVG',
    reviewerName: 'Amazon Customer',
    helpful: [0, 0],
    reviewText:
      "Really shouldn't have Han Solo on the cover as he doesn't come into the story.This story is all about Chewbacca and his family.I won't give anything away, but it is a nice, if short, read.",
    overall: 5.0,
    summary: 'An interesting short story.',
    unixReviewTime: 1392422400,
    reviewTime: '02 15, 2014',
  },

  {
    reviewerID: 'A3SZMGJMV0G16C',
    asin: 'B000FBFMVG',
    reviewerName: 'Andrew Pruette "Rancors Love to Read"',
    helpful: [5, 5],
    reviewText:
      "Originally published as an e-book coinciding with the release of the novel Tatooine Ghost, Troy Denning's A Forest Apart is a short story following Chewbacca, his wife Mallatobuck, and his son Lumpy on a adventure into the bowels of Coruscant. Malla and Lumpy are visiting Chewie at his Coruscant apartment when a break-in at the next-door Solo place turns out to have more serious ramifications. The Wookiees follow the burglars and end up unearthing an Imperial plot set in place by an old tool of the villainous Ysanne Isard.There's a lot of action in a short space but not much time for meaningful character development. Lumpy is a pre-teen striving to find his place in the world, and Chewbacca's perpetual absence in his life may have left a gaping hole as far as having a father figure to look up to. There's not enough pages to explore this theme with much depth, and in the end the issue is dropped, since on a practical level Lumpy can't live with his father chasing all over the galaxy anyway. The theme of the impact a Wookiee Life Debt has on the Wookiee holding it and on his/her family is an interesting one that could be explored in more detail with a longer story.Unlike many novels which handle Chewie's communications by having him grunt and then having a nearby character paraphrase what he said, Denning makes the wise choice of letting the Wookiees speak as normal characters and simply puts brackets to indicate they are actually using their native tongue. It's always enjoyable seeing Chewbacca in action, and even though this story doesn't really add anything significant to the larger saga, it's an entertaining diversion.",
    overall: 3.0,
    summary: "Short story featuring everyone's favorite Wookiee",
    unixReviewTime: 1219622400,
    reviewTime: '08 25, 2008',
  },

  {
    reviewerID: 'A3H8PE1UFK04JZ',
    asin: 'B000FBFMVG',
    reviewerName: 'Caleb Watts',
    helpful: [0, 1],
    reviewText:
      'This book was a good idea. I have always wanted to read more about Chewbaccas son Lumpy. Though I do wish he would have added more to the ending. I would recommend this book to anyone who loves Star Wars and Chewbacca.',
    overall: 4.0,
    summary: 'Great',
    unixReviewTime: 1364774400,
    reviewTime: '04 1, 2013',
  },

  {
    reviewerID: 'A2EN84QHDRZLP2',
    asin: 'B000FBFMVG',
    reviewerName: 'Carl craft',
    helpful: [0, 0],
    reviewText:
      'Great short story. It gives a little more insight into the walking carpet we all love, this time as a father',
    overall: 5.0,
    summary: 'Another read',
    unixReviewTime: 1388620800,
    reviewTime: '01 2, 2014',
  },

  {
    reviewerID: 'A1UG4Q4D3OAH3A',
    asin: 'B000FBFMVG',
    reviewerName: 'dsa',
    helpful: [0, 0],
    reviewText:
      'I love anything with Chewbacca in it.  Him and his family is just a bonus.  Kind of nice to see him having problems with his son.',
    overall: 5.0,
    summary: 'Love It',
    unixReviewTime: 1381449600,
    reviewTime: '10 11, 2013',
  },

  {
    reviewerID: 'A38Z3Q6DTDIH9J',
    asin: 'B000FBFMVG',
    reviewerName: 'Jimmy J. Shaw "oldbent1"',
    helpful: [0, 0],
    reviewText:
      "A great little chapter to read on my Kindle, but not necessarily worth the price. It would have been a nice addition to The Courtship of Princess Leia or an add on to Tatooine Ghost. I liked it, but when it doesn't even rate being published as a paperback; an avid Star Wars fan you will need to be to download and read this eBook.",
    overall: 5.0,
    summary: 'Star Wars: A Forest Apart',
    unixReviewTime: 1239840000,
    reviewTime: '04 16, 2009',
  },

  {
    reviewerID: 'A1ZT7WV0ZUA0OJ',
    asin: 'B000FBFMVG',
    reviewerName: 'Mike',
    helpful: [0, 0],
    reviewText:
      'I love the stories with Chewie in them! this e-book is no exception. great character introductions and wonderful story line.',
    overall: 5.0,
    summary: 'my collection',
    unixReviewTime: 1390780800,
    reviewTime: '01 27, 2014',
  },

  {
    reviewerID: 'A3D58M29K2HWMV',
    asin: 'B000FBFMVG',
    reviewerName: 'P. Thompson "romancewriter"',
    helpful: [0, 0],
    reviewText:
      "I'm not really sure where it actually fits into the overall story line.This story involves only Chewie and his wife and son.  The other characters are only mentioned in passing.  It was enjoyable and well written but I was glad it was very short and didn't keep me from the main story for very long.",
    overall: 4.0,
    summary: 'Enjoyable But...',
    unixReviewTime: 1326499200,
    reviewTime: '01 14, 2012',
  },

  {
    reviewerID: 'A12LKEM543ILBK',
    asin: 'B000FBFMVG',
    reviewerName: 'zombie phreak',
    helpful: [0, 0],
    reviewText:
      "I really do enjoy Troy Denning's work, I want everyone who reads this review to know this.  I loved Star by Star and I very much enjoyed Tattooine Ghost.  This book \"A Forest Apart\" wasn't on par with his other works.  It wasn't without it's charm, but it had things in it that I didn't like.The story itself is pretty simple.  It's a coming of age story for Chewbacca's son, and instead of coming of age on Kashyyyk, he is growing up on Coruscant.  It's not horrible, and we find out that Lumpy is an avid gamer and enjoys playing video games and that he idolizes his father.***SPOILERS***  ***SPOILERS***  ***SPOILERS***First of all, why is Han Solo on the cover?  He's not even IN this story other than a few mentions of his name.  Why not have Chewbacca and Lumpy instead of Han and Chewie?  Also, I HATE books where Chewbacca's grunts and growls are translated.  Like in the Black Fleet Trilogy, he had his speech translated and it was just stupid.  I feel that he works much better as a strong silent type who speaks through his actions rather than his words.  I mean imagine in characters like Jason Vorhees, Michael Meyers, Silent Bob, or Sphynx (from Gone in 60 Seconds), all just started having lengthy conversations throughout their movies?  They lose some of what makes those characters awesome.  Sometimes an author can say very much by having a character say very little.My only other problem with the book is when Chewie and Malla have the droid \"IT\" in their blaster sights, his back is to them and he doesn't see them.  Why don't they just shoot him?  Instead they send Lumpy out as a \"distraction.\"  Yet he doesn't really do anything worth mentioning to distract IT and his minions.  He walks out on the observation deck where they are hiding, opens the window and drops down to the level where IT and his minions are loading nerve gas onto transport ships.  I mean that's not much of a distraction, besides the point of a distraction is to get someone's attention away from one spot so you can do something while they are not looking.  Well, IT wasn't looking in your direction to begin with, so why bother?  They could have just taken up positions on the observation deck and shot him.***END SPOILERS***  ***END SPOILERS***  ***END SPOILERS***Okay so this story wasn't really bad other than a few minor details I didn't like.  I did like seeing that even in a galaxy far far away that we have sons who want to be like their fathers and get into trouble when they do rebellious things.  This story reminded me of what a good writer Troy Denning is and it reminded me to add his other works to my wishlist.Check this one out!",
    overall: 3.0,
    summary: 'A Good Quick Read',
    unixReviewTime: 1365292800,
    reviewTime: '04 7, 2013',
  },

  {
    reviewerID: 'A3SZMGJMV0G16C',
    asin: 'B000FC1BN8',
    reviewerName: 'Andrew Pruette "Rancors Love to Read"',
    helpful: [1, 1],
    reviewText:
      "Timothy Zahn's Fool's Bargain is a short story originally published in e-book form and set before the events of his novel Survivor's Quest. This tale covers an assignment Aurek Company of the Imperial 501st receives on the embattled planet Kariek. The focus is on the four troopers who comprise Aurek-Seven and in particular their leader Twister. This is the same squad that plays a part in Survivor's Quest, minus one personnel change which is detailed in this story. There aren't many Expanded Universe stories that take the Imperial point of view, so this is a welcome perspective here. By this stage in the galaxy's history, years after the Battle of Endor, certain elements of the Empire have developed a more enlightened perspective of the universe around them. These troopers are honorable soldiers fighting for a government they believe in, one that no longer ruthlessly oppresses subject populations but rather plays more of a protector role.The Empire of the films is notably a human-centric organization. Zahn opens the door to alien Imperials in this story with the introduction of Su-mil, an Eickarie and a Kariek native swept up in a civil war. There is a clever bit of deception on Su-mils part involving the Eickarie concept of a lie (they term a lie \"left-handed,\" vs. a truth which is \"right-handed\" - this must be awkward for the native left-handed Eickaries!). By fighting together, Twister sees a potentially valuable ally in Su-mil and we get a perspective of how a stormtrooper unit might be something a soldier would actually aspire to join, rather than simply being cannon fodder for Rebel heroes.All in all, Fool's Bargain is an enjoyable vignette of Imperial life that expands a bit on characters from Survivor's Quest and also provides an interesting preview of the Imperial perspective Zahn went on to explore more thoroughly in his novel Allegiance. It can be purchased in electronic form and is also available in the paperback version ofSurvivor's Quest (Star Wars).",
    overall: 3.0,
    summary: 'Enjoyable Imperial slice-of-life story',
    unixReviewTime: 1285286400,
    reviewTime: '09 24, 2010',
  },

  {
    reviewerID: 'AIG0I95Q2H1GF',
    asin: 'B000FC1BN8',
    reviewerName: 'Anita',
    helpful: [0, 0],
    reviewText:
      "Not too bad, an intro-short-story for some bigger upcoming novel. It's timothy Zahn, what did you expect from the master of Science Fiction.",
    overall: 3.0,
    summary: 'A Short Story',
    unixReviewTime: 1393286400,
    reviewTime: '02 25, 2014',
  },

  {
    reviewerID: 'A3H8PE1UFK04JZ',
    asin: 'B000FC1BN8',
    reviewerName: 'Caleb Watts',
    helpful: [0, 0],
    reviewText:
      'I absolutely love this book. Though it is short it was written by Zahn. Any Star Wars fan knows this book is a good one. I would recommend this book to anyone who loves Star Wars.',
    overall: 5.0,
    summary: 'Great',
    unixReviewTime: 1364774400,
    reviewTime: '04 1, 2013',
  },

  {
    reviewerID: 'A1UG4Q4D3OAH3A',
    asin: 'B000FC1BN8',
    reviewerName: 'dsa',
    helpful: [0, 0],
    reviewText:
      'What can I say Stormtroopers.  A story with troopers is as awesome as a story with any Sith lord.  AWESOME!!!!!!',
    overall: 5.0,
    summary: 'Stormtroopers',
    unixReviewTime: 1381449600,
    reviewTime: '10 11, 2013',
  },

  {
    reviewerID: 'AQZH7YTWQPOBE',
    asin: 'B000FC1BN8',
    reviewerName: 'Enjolras',
    helpful: [8, 9],
    reviewText:
      "For whatever reason, Star Wars short stories are a bit of a hit or miss. The \"Tales of...\" are great in that they explain background characters. However,Fool's Bargaindidn't really fit the bill. It's a short story about a relatively minor and unmemorable character from Timothy Zahn'sSurvivor's Quest (Star Wars). The story itself is basically about stormtroopers storming a fortress with some mysterious Warlord. Unlike most of Zahn's other work, this is mostly a book of action, not intricate plot development. In fact, the story ends with an exciting twist, but doesn't develop it. I feel like this short story would have been better had it been about a character we all know and love, or included a really interesting plot twist. Also, just to note, this same story is included in the paperback copy ofSurvivor's Quest (Star Wars), so there's no need to buy the separate Kindle version.",
    overall: 2.0,
    summary: 'Too short, not enough story',
    unixReviewTime: 1285286400,
    reviewTime: '09 24, 2010',
  },

  {
    reviewerID: 'A38Z3Q6DTDIH9J',
    asin: 'B000FC1BN8',
    reviewerName: 'Jimmy J. Shaw "oldbent1"',
    helpful: [0, 2],
    reviewText:
      "As an ebook it reads very well on my Kindle, but it really doesn't seem to belong where it is. Maybe at the end of The Dark Nest Trilogy or Legacy of the Force, but it just seems not to have a place it belongs in the Star Wars universe. At least not to me.",
    overall: 3.0,
    summary: "Star Wars: Fool's Bargain",
    unixReviewTime: 1239840000,
    reviewTime: '04 16, 2009',
  },

  {
    reviewerID: 'A2OIGPPBTR65MR',
    asin: 'B000FC1BN8',
    reviewerName: 'para',
    helpful: [0, 0],
    reviewText:
      "** Note: this story appears as a bonus in the paperback edition of Survivor's Quest. **Fool's Bargain is a short story featuring the stormtroopers of Aurek-Four, a unit of the Imperial 501st Legion of the Empire of the Hand.  It takes place shortly before the events of Survivor's Quest, but is probably best read after.The Empire of the Hand is involved in a war to rid the native Eickarie people of their latest warlord, but the 501st curious orders are very specific - take the warlord alive.  This story is tightly focused, with a couple of characters firmly at the center.  There's good detail here but for some reason it doesn't feel as well developed as other short stories I've read by Zahn.  Also,  those who look for big names in their Star Wars stories will want to give this a pass.  A couple of minor characters from Survivor's Quest show up in largely supporting roles, but there are no movie characters nor beloved favorites here.But despite these caveats Fool's Bargain is a good short story that gives further glimpse of Zahn's take on stormtroopers, which he touched on in Survivor's Quest, and would continue to explore in later novels (Allegiance and Choices of One).",
    overall: 3.0,
    summary: 'Enjoyable, if unremarkable, stormtrooper tale.',
    unixReviewTime: 1336953600,
    reviewTime: '05 14, 2012',
  },

  {
    reviewerID: 'A1YEPFLLH42OU1',
    asin: 'B000FC1BN8',
    reviewerName: 'Yu-jin &amp; Tracy Chia "Yu-Jin Chia"',
    helpful: [0, 0],
    reviewText:
      "I admit it, I snapped this up the moment I saw it on new releases, because I tend to do that with anything written by Timothy Zahn. He is, in my opinion, one of the best contemporary sci-fi authors where it comes to world building, intricate plot, and edge-of-seat action. His Thrawn and Conqueror's trilogies were incredible, Quadrail and Cobra were very unique and engaging, and even his one-off novels like Icarus Hunt and Outbound Flight are excellent. So I figured this would be too.First off, when I hit the end my jaw dropped and I literally said aloud \"Huh? That's it?!\" I then spent several minutes looking to see if it picked up somewhere else. It is a really short story, barely longer than some of the ones that appear in the 'Tales' Star Wars series (and those books have several of them!). It's also, I must say, a lot less interesting than most of them and probably the single weakest plot I've seen Zahn write. It's not terrible, but it really isn't that great either- there's no twists and at the end you're left wondering where the other half of the story is. The novella revolves around a force of Stormtroopers who are only somewhat memorable (as is the case with most such white-armored shock troops) and though there is quite a bit of action, it kind of reads like a (short) movie or videogame script.Overall, not worth paying for. In fact, it should really be free if you ask me.",
    overall: 2.0,
    summary: 'An average short story',
    unixReviewTime: 1358380800,
    reviewTime: '01 17, 2013',
  },

  {
    reviewerID: 'A12LKEM543ILBK',
    asin: 'B000FC1BN8',
    reviewerName: 'zombie phreak',
    helpful: [0, 0],
    reviewText:
      "I love Timothy Zahn's work!  He does what no other writer, not even George Lucas himself can do.  He takes the rank and file Storm Troopers and gives them personalities, talents, skills and makes them multi-dimensional characters that people can get invested in.Where most writers show the Storm Troopers as faceless cannon fodder who can't hit anything with their blasters, Zahn shows them as competent sharpshooting elite commandos who can think on their feet and adapt to any situation as well as follow orders.***SPOILERS***  ***SPOILERS***  ***SPOILERS***So the story is a pretty basic one.  There is an alien warlord who is ruling a planet with an iron fist, and the Empire decides it is time to go and free the plant of his rule, so they dispatch the 501st Legion a.k.a. Vader's Fist to take him down.There is something I do wonder about though, this takes place after Vader is dead, and after Thrawn's rule has ended.  So why does the 501st Legion keep calling themselves \"Vader's Fist?\"  Vader's not around anymore?  Do they keep the name just for the sake of nostalgia?  It's not really a major gripe, just something that makes me scratch my head.Our main characters are three Storm Troopers who all have different skills and specialties.  They infiltrate the warlord's fortress and meet up with some of the local freedom fighters and strike a deal with them.  If the troopers help them free their imprisoned comrades, they will help the troopers get inside and take out the warlord's troops and bring him to justice.The troopers agree and they infiltrate the stronghold together.  Later it seems the rebels have betrayed the Storm Troopers, but it turns out it is just a very elaborate ruse and the rebels were always on the side of the troopers and the prisoners are freed and the warlord is captured by the Empire and brought to justice.Later the head of the rebels is offered a position in the 501st Legion, which is awesome!  It really helps to enforce the fact that the Empire has learned that just having humans in their military doesn't help, it's a hindrance and it was the main reason the Rebel Alliance was able to defeat them.***END SPOILERS***  ***END SPOILERS***  ***END SPOILERS***Zahn gives us action, gun fights, intrigue and a little bit of politics as well in this story.  Any fan of Star Wars or Zahn's writing will enjoy this book very much!",
    overall: 5.0,
    summary: 'Excellent!',
    unixReviewTime: 1368748800,
    reviewTime: '05 17, 2013',
  },

  {
    reviewerID: 'AVWWFK3FZDEL2',
    asin: 'B000FC1TG2',
    reviewerName: 'D. Mckinzie',
    helpful: [0, 0],
    reviewText:
      "The hero in this story has been living in NYC and working for a sort of Crime boss.  Beaten up and tossed in an empty train car by the competition, he ends up out west and, by a series of flukes, becomes the sheriff of a small western town that is in serious trouble.  While it is not one of my L'Amour favorites, he tells it with his usual flair and attention to detail and it's well worth reading.",
    overall: 5.0,
    summary: 'Unlikely, but possible, story, very well told',
    unixReviewTime: 1362960000,
    reviewTime: '03 11, 2013',
  },

  {
    reviewerID: 'A1CQ8WG6CUDBNV',
    asin: 'B000FC1TG2',
    reviewerName: 'gail',
    helpful: [0, 0],
    reviewText:
      'The Iron Marshall, by Louie L`Amour is one of his best. Of course all of his are the best.Louie is a man who knew the west. His books make it possible to really feel how it was.',
    overall: 5.0,
    summary: 'Gail',
    unixReviewTime: 1395964800,
    reviewTime: '03 28, 2014',
  },

  {
    reviewerID: 'A1XWEAEETTS4OD',
    asin: 'B000FC1TG2',
    reviewerName: 'John H. Danner "Book Lover"',
    helpful: [0, 0],
    reviewText:
      "This is yet another  L'Amour winner. I have yet to read a book of his that was less than great. He has the ability to keep you enthalled enough in the story to make you not want to put the book down until it is finished.",
    overall: 5.0,
    summary: 'Great Read',
    unixReviewTime: 1386374400,
    reviewTime: '12 7, 2013',
  },

  {
    reviewerID: 'A3B07KAS0C0Q2R',
    asin: 'B000FC1TG2',
    reviewerName: 'Kindle Customer',
    helpful: [0, 0],
    reviewText:
      "I almost didn't get this book because of the cover but since it was double 'LL  I did.  As always the author came through.  Good book and characters.  The plot was interesting",
    overall: 5.0,
    summary: 'Irish luck',
    unixReviewTime: 1371513600,
    reviewTime: '06 18, 2013',
  },

  {
    reviewerID: 'AWYOWZKRBKQHQ',
    asin: 'B000FC1TG2',
    reviewerName: 'Mary Ellison',
    helpful: [0, 0],
    reviewText:
      "This story by Louis L'Amour was the very first of his novels that I ever read.  Novels with a western theme were not my thing when I was growning up, so imagine my surprise when I just sort of drifted into this book one rainy afternoon.  I guess I was attracted to it by the fact that it opens in New York City, not the deserts of New Mexico.Anyway, I soon found that L'Amour has a writing style just as smooth as silk, and I found myself sliding into this book as easily as if he took me by the hand and led me to an alter.  Since then I have read several more of L'Amour's books and have enjoyed all of them.  I will review them here over the next few weeks, time permitting.This book tells the story of how a young man from New York City ends up in a small Kansas town and picks up the job of being the Sheriff one day before all hell is scheduled to break loose.  Others have outlined the text already, so I won't bore you with yet another outline.  I'll just say that if you have not read any of Louis L'Amour in the past, this would be a really great place to start, or even to get reacquainted.  While you do that, I'm gonna find another L'Amour book to read.:)",
    overall: 5.0,
    summary: 'A Good Afternoon Read',
    unixReviewTime: 1248480000,
    reviewTime: '07 25, 2009',
  },

  {
    reviewerID: 'AEC18J7P03ZBP',
    asin: 'B000FC1TG2',
    reviewerName: 'pigskin',
    helpful: [0, 0],
    reviewText:
      'This is how it was in the big gambling and corrupt cities of the eastern seaboard.  Then go out west and become a real hero.  Again, the video was also good.',
    overall: 5.0,
    summary: 'Wow what a transition!',
    unixReviewTime: 1369785600,
    reviewTime: '05 29, 2013',
  },
];

export const reviews = REVIEWS.reduce<
  { asin: string; overallRating: number; reviews: BookReview[] }[]
>((all, currentValue) => {
  const book = all.find((book) => book.asin === currentValue.asin);
  const { asin, ...review } = currentValue;
  if (book) {
    book.reviews.push(review);
    book.overallRating += review.overall;
  } else {
    all.push({
      asin,
      overallRating: review.overall,
      reviews: [review],
    });
  }
  return all;
}, []);
